export const STARTUP_SPHERES = [
  'EdTech',
  'R&D',
  'RetailTech',
  'Hardware',
  'MedTech',
  'GameDev',
  'TravelTech',
  'HR Tech',
  'SocialTech',
  'AI',
  'AgriTech',
  'PropTech',
  'FinTech',
  'GovTech',
  'SaaS',
  'E-commerce',
  'Marketplace',
  'ERP',
  'SportTech',
  'CyberSecurity',
  'AdTech',
  'CleanTech',
  'EventTech',
  'HealthTech',
  'LogiTech',
  'HomeTech',
  'LegalTech',
  'InsurTech',
  'FoodTech',
  'MobilityTech',
  'SpaceTech',
  'BioTech',
  'WealthTech',
  'ConTech',
] as const;

export const DEFAULT_STARTUP_SPHERE = STARTUP_SPHERES[0];
